#!/usr/bin/env bash
set -e

ARCH=$(uname -m | tr '[:lower:]' '[:upper:]')
OS=$(uname -s)

if [[ "$ARCH" == "X86_64" && "$OS" == "Linux" ]]; then
    BINARY_FILENAME="elm-generator-linux-x64.tar.gz"
elif [[ ( "$ARCH" == "AARCH64" || "$ARCH" == "ARM64" ) && "$OS" == "Linux" ]]; then
    BINARY_FILENAME="elm-generator-linux-arm64.tar.gz"
elif [[ "$ARCH" == "ARM64" && "$OS" == "Darwin" ]]; then
    BINARY_FILENAME="elm-generator-osx-arm64.tar.gz"
else
    echo "❌ Unsupported architecture or OS: $ARCH / $OS" >&2
    exit 1
fi

curl --fail -L -H "Authorization: token ${SPOTIFY_ALBUM_REPO_ACCESS_TOKEN}" -o main.zip https://api.github.com/repos/AlbumShuffler/Albums/zipball/main
rm -rf temp
unzip -qq -d temp main.zip
rm -rf albums
mv temp/*/output albums
rm -rf temp

latest_tag=$(curl -sL https://api.github.com/repos/AlbumShuffler/Tools/tags | jq -r '.[0].name')
echo "Trying to download latest elm-generator: ${latest_tag}"
download_url=$(echo -e "https://github.com/AlbumShuffler/Tools/releases/download/${latest_tag}/${BINARY_FILENAME}")
wget $download_url
rm -rf elm-generator
mkdir elm-generator
tar -xf ${BINARY_FILENAME} -C elm-generator
rm ${BINARY_FILENAME}


cd elm-generator
echo "Running elm generator"
./AlbumShuffler.ElmGenerator ../albums ../src
cd ..
rm -rf elm-generator
